services:
 
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /Users/janepavlova/LocalDataVolumes/ApiShowcaseData:/var/lib/postgresql/data
